In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv("https://pycourse.s3.amazonaws.com/Data.csv")
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
#Formatar o print do numpy
np.set_printoptions(precision=4, suppress=True)

In [9]:
#Trocando os dados faltantes pela média
imputer = SimpleImputer(strategy = 'mean')
num_cols_mean = imputer.fit_transform(df[['Age', 'Salary']])
num_cols_mean

array([[   44.    , 72000.    ],
       [   27.    , 48000.    ],
       [   30.    , 54000.    ],
       [   38.    , 61000.    ],
       [   40.    , 63777.7778],
       [   35.    , 58000.    ],
       [   38.7778, 52000.    ],
       [   48.    , 79000.    ],
       [   50.    , 83000.    ],
       [   37.    , 67000.    ]])

In [10]:
#Trocando os dados faltantes pela mediana
imputer = SimpleImputer(strategy = 'median')
num_cols_median = imputer.fit_transform(df[['Age', 'Salary']])
num_cols_median

array([[   44., 72000.],
       [   27., 48000.],
       [   30., 54000.],
       [   38., 61000.],
       [   40., 61000.],
       [   35., 58000.],
       [   38., 52000.],
       [   48., 79000.],
       [   50., 83000.],
       [   37., 67000.]])

In [11]:
df[['Age', 'Salary']] = num_cols_median
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
#Normalização de Dados numéricos

from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [14]:
sc = StandardScaler()
num_cols_std = sc.fit_transform(df[['Age','Salary']])
num_cols_std

array([[ 0.7697,  0.7726],
       [-1.6992, -1.4088],
       [-1.2635, -0.8635],
       [-0.1017, -0.2272],
       [ 0.1888, -0.2272],
       [-0.5374, -0.4999],
       [-0.1017, -1.0452],
       [ 1.3507,  1.4088],
       [ 1.6411,  1.7724],
       [-0.2469,  0.3181]])

In [15]:
#Escalando dados numéricos entre o Min e Max
minmax = MinMaxScaler(feature_range=(0,1))
num_cols_mm = minmax.fit_transform(df[['Age','Salary']])
num_cols_mm

array([[0.7391, 0.6857],
       [0.    , 0.    ],
       [0.1304, 0.1714],
       [0.4783, 0.3714],
       [0.5652, 0.3714],
       [0.3478, 0.2857],
       [0.4783, 0.1143],
       [0.913 , 0.8857],
       [1.    , 1.    ],
       [0.4348, 0.5429]])