In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Dados/cmc.csv")

In [4]:
df.head()

Wifes_age  Wifes_education  Husbands_education  \
0         24                2                   3   
1         45                1                   3   
2         43                2                   3   
3         42                3                   2   
4         36                3                   3   

   Number_of_children_ever_born  Wifes_religion  Wifes_now_working%3F  \
0                             3               1                     1   
1                            10               1                     1   
2                             7               1                     1   
3                             9               1                     1   
4                             8               1                     1   

   Husbands_occupation  Standard-of-living_index  Media_exposure  \
0                    2                         3               0   
1                    3                         4               0   
2                    3                         4               0   
3                    3                         3               0   
4                    3                         2               0   

   Contraceptive_method_used  
0                          1  
1                          1  
2                          1  
3                          1  
4                          1

In [5]:
df.shape

(1473, 10)

In [6]:
df.columns

Index(['Wifes_age', 'Wifes_education', 'Husbands_education',
       'Number_of_children_ever_born', 'Wifes_religion',
       'Wifes_now_working%3F', 'Husbands_occupation',
       'Standard-of-living_index', 'Media_exposure',
       'Contraceptive_method_used'],
      dtype='object')

In [7]:
#Criando um dicionário
name_to_class = {
    1: 0,
    2: 1,
    3: 2
}

df['Contraceptive_method_used'] = df['Contraceptive_method_used'].map(name_to_class)

In [8]:
#Binarizando as Features
df1 = pd.get_dummies(df, columns=['Wifes_education', 'Husbands_education', 'Wifes_religion',
                                 'Wifes_now_working%3F', 'Husbands_occupation', 'Standard-of-living_index',
                                 'Media_exposure'])

df1.head()

Wifes_age  Number_of_children_ever_born  Contraceptive_method_used  \
0         24                             3                          0   
1         45                            10                          0   
2         43                             7                          0   
3         42                             9                          0   
4         36                             8                          0   

   Wifes_education_1  Wifes_education_2  Wifes_education_3  Wifes_education_4  \
0                  0                  1                  0                  0   
1                  1                  0                  0                  0   
2                  0                  1                  0                  0   
3                  0                  0                  1                  0   
4                  0                  0                  1                  0   

   Husbands_education_1  Husbands_education_2  Husbands_education_3  ...  \
0                     0                     0                     1  ...   
1                     0                     0                     1  ...   
2                     0                     0                     1  ...   
3                     0                     1                     0  ...   
4                     0                     0                     1  ...   

   Husbands_occupation_1  Husbands_occupation_2  Husbands_occupation_3  \
0                      0                      1                      0   
1                      0                      0                      1   
2                      0                      0                      1   
3                      0                      0                      1   
4                      0                      0                      1   

   Husbands_occupation_4  Standard-of-living_index_1  \
0                      0                           0   
1                      0                           0   
2                      0                           0   
3                      0                           0   
4                      0                           0   

   Standard-of-living_index_2  Standard-of-living_index_3  \
0                           0                           1   
1                           0                           0   
2                           0                           0   
3                           0                           1   
4                           1                           0   

   Standard-of-living_index_4  Media_exposure_0  Media_exposure_1  
0                           0                 1                 0  
1                           1                 1                 0  
2                           1                 1                 0  
3                           0                 1                 0  
4                           0                 1                 0  

[5 rows x 25 columns]

In [9]:
df.describe()

Wifes_age  Wifes_education  Husbands_education  \
count  1473.000000      1473.000000         1473.000000   
mean     32.538357         2.958588            3.429735   
std       8.227245         1.014994            0.816349   
min      16.000000         1.000000            1.000000   
25%      26.000000         2.000000            3.000000   
50%      32.000000         3.000000            4.000000   
75%      39.000000         4.000000            4.000000   
max      49.000000         4.000000            4.000000   

       Number_of_children_ever_born  Wifes_religion  Wifes_now_working%3F  \
count                   1473.000000     1473.000000           1473.000000   
mean                       3.261371        0.850645              0.749491   
std                        2.358549        0.356559              0.433453   
min                        0.000000        0.000000              0.000000   
25%                        1.000000        1.000000              0.000000   
50%                        3.000000        1.000000              1.000000   
75%                        4.000000        1.000000              1.000000   
max                       16.000000        1.000000              1.000000   

       Husbands_occupation  Standard-of-living_index  Media_exposure  \
count          1473.000000               1473.000000     1473.000000   
mean              2.137814                  3.133741        0.073999   
std               0.864857                  0.976161        0.261858   
min               1.000000                  1.000000        0.000000   
25%               1.000000                  3.000000        0.000000   
50%               2.000000                  3.000000        0.000000   
75%               3.000000                  4.000000        0.000000   
max               4.000000                  4.000000        1.000000   

       Contraceptive_method_used  
count                1473.000000  
mean                    0.919891  
std                     0.876376  
min                     0.000000  
25%                     0.000000  
50%                     1.000000  
75%                     2.000000  
max                     2.000000

In [10]:
df1.describe()

Wifes_age  Number_of_children_ever_born  Contraceptive_method_used  \
count  1473.000000                   1473.000000                1473.000000   
mean     32.538357                      3.261371                   0.919891   
std       8.227245                      2.358549                   0.876376   
min      16.000000                      0.000000                   0.000000   
25%      26.000000                      1.000000                   0.000000   
50%      32.000000                      3.000000                   1.000000   
75%      39.000000                      4.000000                   2.000000   
max      49.000000                     16.000000                   2.000000   

       Wifes_education_1  Wifes_education_2  Wifes_education_3  \
count        1473.000000        1473.000000        1473.000000   
mean            0.103191           0.226748           0.278344   
std             0.304311           0.418871           0.448336   
min             0.000000           0.000000           0.000000   
25%             0.000000           0.000000           0.000000   
50%             0.000000           0.000000           0.000000   
75%             0.000000           0.000000           1.000000   
max             1.000000           1.000000           1.000000   

       Wifes_education_4  Husbands_education_1  Husbands_education_2  \
count        1473.000000           1473.000000           1473.000000   
mean            0.391718              0.029871              0.120842   
std             0.488300              0.170289              0.326054   
min             0.000000              0.000000              0.000000   
25%             0.000000              0.000000              0.000000   
50%             0.000000              0.000000              0.000000   
75%             1.000000              0.000000              0.000000   
max             1.000000              1.000000              1.000000   

       Husbands_education_3  ...  Husbands_occupation_1  \
count           1473.000000  ...            1473.000000   
mean               0.238968  ...               0.295995   
std                0.426598  ...               0.456644   
min                0.000000  ...               0.000000   
25%                0.000000  ...               0.000000   
50%                0.000000  ...               0.000000   
75%                0.000000  ...               1.000000   
max                1.000000  ...               1.000000   

       Husbands_occupation_2  Husbands_occupation_3  Husbands_occupation_4  \
count            1473.000000            1473.000000            1473.000000   
mean                0.288527               0.397149               0.018330   
std                 0.453231               0.489473               0.134187   
min                 0.000000               0.000000               0.000000   
25%                 0.000000               0.000000               0.000000   
50%                 0.000000               0.000000               0.000000   
75%                 1.000000               1.000000               0.000000   
max                 1.000000               1.000000               1.000000   

       Standard-of-living_index_1  Standard-of-living_index_2  \
count                 1473.000000                 1473.000000   
mean                     0.087576                    0.155465   
std                      0.282774                    0.362470   
min                      0.000000                    0.000000   
25%                      0.000000                    0.000000   
50%                      0.000000                    0.000000   
75%                      0.000000                    0.000000   
max                      1.000000                    1.000000   

       Standard-of-living_index_3  Standard-of-living_index_4  \
count                 1473.000000                 1473.000000   
mean                     0.292600                    0.464358   
std                      0.455111    

In [11]:
labels = np.array(df['Contraceptive_method_used'])
feauture_list = list(df.columns)

In [12]:
#Removendo a coluna de labels do df original
df = df.drop('Contraceptive_method_used', axis=1)
df.columns

Index(['Wifes_age', 'Wifes_education', 'Husbands_education',
       'Number_of_children_ever_born', 'Wifes_religion',
       'Wifes_now_working%3F', 'Husbands_occupation',
       'Standard-of-living_index', 'Media_exposure'],
      dtype='object')

In [13]:
#Converter o Df para um array
data = np.array(df)

In [14]:
#REPETINDO TUDO PARA DF1
labels1 = np.array(df1['Contraceptive_method_used'])
feauture_list = list(df1.columns)

In [15]:
#Removendo a coluna de labels do df original
df1 = df1.drop('Contraceptive_method_used', axis=1)
df1.columns

Index(['Wifes_age', 'Number_of_children_ever_born', 'Wifes_education_1',
       'Wifes_education_2', 'Wifes_education_3', 'Wifes_education_4',
       'Husbands_education_1', 'Husbands_education_2', 'Husbands_education_3',
       'Husbands_education_4', 'Wifes_religion_0', 'Wifes_religion_1',
       'Wifes_now_working%3F_0', 'Wifes_now_working%3F_1',
       'Husbands_occupation_1', 'Husbands_occupation_2',
       'Husbands_occupation_3', 'Husbands_occupation_4',
       'Standard-of-living_index_1', 'Standard-of-living_index_2',
       'Standard-of-living_index_3', 'Standard-of-living_index_4',
       'Media_exposure_0', 'Media_exposure_1'],
      dtype='object')

In [16]:
#Converter o Df para um array
data1 = np.array(df)

In [17]:
from sklearn.model_selection import train_test_split

#Divindo em treino e teste as duas bases, binarizada e não binzarizada
train_data, test_data, train_labels, test_labels = train_test_split(df, labels, test_size= 0.25, random_state = 42)

train_data1, test_data1, train_labels1, test_labels1 = train_test_split(df1, labels1, test_size = 0.25, random_state = 42)

In [18]:
#BASELINE: COMPARANDO COM UM MODELO ALEATORIO
baseline_preds = np.random.choice([0,1,2], size = len(test_labels))
print(baseline_preds)

[1 1 2 1 0 2 2 1 0 2 0 2 1 0 1 1 1 1 2 0 0 0 0 1 0 0 2 0 2 2 1 0 0 0 0 1 0
 2 2 1 0 2 0 1 1 2 1 1 2 1 0 1 2 2 2 1 1 2 2 1 1 2 1 0 1 1 1 0 0 1 0 1 1 1
 0 0 0 1 1 2 1 1 0 1 2 1 1 0 2 1 0 1 2 1 2 1 2 2 2 0 1 2 1 2 1 2 1 0 1 1 1
 1 0 1 1 1 1 0 0 1 0 2 1 0 0 1 2 1 2 0 0 1 1 1 0 2 0 0 0 2 0 0 2 0 2 1 2 1
 0 0 1 0 1 0 0 1 0 0 1 2 2 0 2 2 1 2 1 2 1 1 1 1 1 1 2 2 2 2 2 0 2 1 2 1 1
 2 1 2 2 0 0 0 1 2 1 1 2 1 0 1 0 1 0 2 1 2 0 0 2 1 2 1 1 2 0 1 1 0 2 1 1 1
 2 1 2 2 2 0 1 2 0 0 0 2 2 0 1 0 1 0 1 2 0 1 2 2 2 2 1 0 0 2 0 0 0 1 1 2 0
 1 0 2 2 0 2 0 2 0 1 0 0 0 1 1 1 2 1 2 2 2 0 0 1 1 0 2 0 2 2 1 2 1 1 2 1 2
 0 1 2 0 0 0 2 1 0 1 0 0 2 0 2 0 1 1 0 1 2 0 1 1 1 0 2 0 0 0 1 0 1 0 1 2 2
 0 0 0 2 0 0 0 1 1 0 2 1 0 2 1 1 1 0 2 2 0 2 2 1 1 0 1 1 2 1 2 1 0 0 1 0]


In [20]:
from sklearn import metrics 
from sklearn.metrics import cluster

#Avaliando o Baseline

#Ponto de Vista Não Supervisionado
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data, baseline_preds))
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data, baseline_preds))

#Ponto de Vista Supervisionado
print('\nMatriz de Contigência\n', metrics.cluster.contingency_matrix(test_labels, baseline_preds))
print('\nMutual Information\n', metrics.mutual_info_score(test_labels, baseline_preds))


Coeficiente de Silhueta
 -0.01691156727358094

Davies-Bouldin Score
 30.753903428823588

Matriz de Contigência
 [[58 65 36]
 [31 29 27]
 [32 46 45]]

Mutual Information
 0.011289798509767884


In [24]:
#K-MEANS
from sklearn.cluster import KMeans

clustering = KMeans(n_clusters=3, random_state=42)
#treinando o Modelo com a base de dados não binzarizado
clustering.fit(train_data)

KMeans(n_clusters=3, random_state=42)

In [25]:
#Predições
predicition1_labels = clustering.predict(test_data)

#Exibindo dataframe com real e previto
p = pd.DataFrame({'Real': test_labels, 'Previsto': predicition1_labels})
p.head(10)

Real  Previsto
0     2         1
1     0         0
2     1         1
3     0         0
4     0         1
5     1         1
6     1         1
7     0         1
8     0         0
9     0         1

In [26]:
#Avaliando o Modelo K-means, com a base de dados não binarizada

#Ponto de Vista Não Supervisionado
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data, predicition1_labels))
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data, predicition1_labels))

#Ponto de Vista Supervisionado
print('\nMatriz de Contigência\n', metrics.cluster.contingency_matrix(test_labels, predicition1_labels))
print('\nMutual Information\n', metrics.mutual_info_score(test_labels, predicition1_labels))

Coeficiente de Silhueta
 0.44398567322815014

Davies-Bouldin Score
 0.7497426781124615

Matriz de Contigência
 [[52 67 40]
 [41 28 18]
 [49 65  9]]

Mutual Information
 0.030770654164656755


In [28]:
#Kmeans (BINZARIZADO)
clustering = KMeans(n_clusters=3, random_state=42)
#treinando o Modelo com a base de dados binzarizada
clustering.fit(train_data1)

KMeans(n_clusters=3, random_state=42)

In [29]:
#Predições
predicition1_labels = clustering.predict(test_data1)

#Exibindo dataframe com real e previto
p = pd.DataFrame({'Real': test_labels1, 'Previsto': predicition1_labels})
p.head(10)

Real  Previsto
0     2         0
1     0         2
2     1         0
3     0         2
4     0         0
5     1         0
6     1         0
7     0         0
8     0         2
9     0         0

In [31]:
#Avaliando o Modelo K-means, com a base de dados binarizada

#Ponto de Vista Não Supervisionado
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data1, predicition1_labels))
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data1, predicition1_labels))

#Ponto de Vista Supervisionado
print('\nMatriz de Contigência\n', metrics.cluster.contingency_matrix(test_labels1, predicition1_labels))
print('\nMutual Information\n', metrics.mutual_info_score(test_labels1, predicition1_labels))

Coeficiente de Silhueta
 0.4464717655880375

Davies-Bouldin Score
 0.7429468747878573

Matriz de Contigência
 [[67 40 52]
 [28 18 41]
 [65  9 49]]

Mutual Information
 0.030770654164656755


In [34]:
#Affinity Propagation
from sklearn.cluster import AffinityPropagation

#Criando e treinando um modelo com a base de dados não binzariazada
clustering = AffinityPropagation(random_state=42).fit(train_data)

In [36]:
#Predição
predicition2_labels = clustering.predict(test_data)

In [42]:
#Avaliando o Modelo para a base não Binzarizada

#Ponto de Vista Não Supervisionado
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data, predicition2_labels))
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data, predicition2_labels))

#Ponto de Vista Supervisionado
print('\nMatriz de Contigência\n', metrics.cluster.contingency_matrix(test_labels, predicition2_labels))
print('\nMutual Information\n', metrics.mutual_info_score(test_labels, predicition2_labels))

Coeficiente de Silhueta
 0.10515487228401682

Davies-Bouldin Score
 1.6944923706806492

Matriz de Contigência
 [[ 5  3  9  7  5  4  5 10  5  0 11  1  1  2  7  4  1  3  8  3  2  9 11  4
   7 12  4 13  3]
 [ 2  9  3  2  4  4  0  9 11  2  8  0  2  4  3  0  2  0  3  2  0  5  0  2
   0  5  0  5  0]
 [ 2  4 12 13  1  8  3  7  4  3 10  0  5  6  1  2  0  1  3  1  0  5  9  7
   0  7  0  0  9]]

Mutual Information
 0.1816368535726044


In [38]:
#Criando e treinando um modelo com a base de dados  binzariazada
clustering = AffinityPropagation(random_state=42).fit(train_data1)

In [39]:
#Predição
predicition2_labels = clustering.predict(test_data1)

In [43]:
#Avaliando o Modelo para a base Binzarizada

#Ponto de Vista Não Supervisionado
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data1, predicition2_labels))
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data1, predicition2_labels))

#Ponto de Vista Supervisionado
print('\nMatriz de Contigência\n', metrics.cluster.contingency_matrix(test_labels1, predicition2_labels))
print('\nMutual Information\n', metrics.mutual_info_score(test_labels1, predicition2_labels))

Coeficiente de Silhueta
 0.10399502121555088

Davies-Bouldin Score
 1.6801102221551072

Matriz de Contigência
 [[ 5  3  9  7  5  4  5 10  5  0 11  1  1  2  7  4  1  3  8  3  2  9 11  4
   7 12  4 13  3]
 [ 2  9  3  2  4  4  0  9 11  2  8  0  2  4  3  0  2  0  3  2  0  5  0  2
   0  5  0  5  0]
 [ 2  4 12 13  1  8  3  7  4  3 10  0  5  6  1  2  0  1  3  1  0  5  9  7
   0  7  0  0  9]]

Mutual Information
 0.1816368535726044
