In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
df_reg = pd.read_csv("Dados/diabetes_numeric.csv")
df_class = pd.read_csv("Dados/bloodtransf.csv")
df_cluster = pd.read_csv("Dados/wine.csv")

In [4]:
df_reg.shape

(43, 3)

In [5]:
# Sobre o número de atributos da base de regressão, marque a alternativa CORRETA: 
df_reg.head()

age  deficit  c_peptide
0   5.2     -8.1        4.8
1   8.8    -16.1        4.1
2  10.5     -0.9        5.2
3  10.6     -7.8        5.5
4  10.4    -29.0        5.0

In [7]:
# Sobre o número de instâncias da base de classificação, marque a alternativa CORRETA: 
df_class.shape

(748, 5)

In [9]:
#Sobre a base de clusterização, marque a alternativa CORRETA: 
df_cluster.shape

(178, 14)

In [10]:
df_cluster.head()

class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280%2FOD315_of_diluted_wines  Proline  
0             5.64  1.04                            3.92     1065  
1             4.38  1.05                            3.40     1050  
2             5.68  1.03                            3.17     1185  
3             7.80  0.86                            3.45     1480  
4             4.32  1.04                            2.93      735

In [11]:
df_cluster.describe()

class     Alcohol  Malic_acid         Ash  Alcalinity_of_ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000   
mean     1.938202   13.000618    2.336348    2.366517          19.494944   
std      0.775035    0.811827    1.117146    0.274344           3.339564   
min      1.000000   11.030000    0.740000    1.360000          10.600000   
25%      1.000000   12.362500    1.602500    2.210000          17.200000   
50%      2.000000   13.050000    1.865000    2.360000          19.500000   
75%      3.000000   13.677500    3.082500    2.557500          21.500000   
max      3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total_phenols  Flavanoids  Nonflavanoid_phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color_intensity         Hue  \
count       178.000000       178.000000  178.000000   
mean          1.590899         5.058090    0.957449   
std           0.572359         2.318286    0.228572   
min           0.410000         1.280000    0.480000   
25%           1.250000         3.220000    0.782500   
50%           1.555000         4.690000    0.965000   
75%           1.950000         6.200000    1.120000   
max           3.580000        13.000000    1.710000   

       OD280%2FOD315_of_diluted_wines      Proline  
count                      178.000000   178.000000  
mean                         2.611685   746.893258  
std                          0.709990   314.907474  
min                          1.270000   278.000000  
25%                          1.937500   500.500000  
50%                          2.780000   673.500000  
75%                          3.170000   985.000000  
max                          4.000000  1680.000000

In [13]:
# Em relação a modelagem utilizando a regressão linear, marque a alternativa CORRETA sobre a métrica r2:
labels = np.array(df_reg['c_peptide'])

#ordem das feautures
feauture_list = list(df_reg.columns)

In [14]:
#Removendo a coluna alvo do df
df_reg = df_reg.drop('c_peptide', axis=1)

In [15]:
data_reg = np.array(df_reg)

In [16]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_labels, test_labels = train_test_split(data_reg, labels, test_size=0.35, random_state = 54)

In [17]:
from sklearn.linear_model import LinearRegression

#treinando o modelo
regression = LinearRegression().fit(train_data, train_labels)

In [18]:
#Predição
predictions1_labels = regression.predict(test_data)

In [21]:
#Avaliando o Modelo 
from sklearn import metrics
print("R2: ", metrics.r2_score(test_labels, predictions1_labels))

R2:  0.2730761502482787


In [22]:
# Em relação a modelagem utilizando a regressão linear, marque a alternativa CORRETA sobre a métrica MAE:  
print("MAE: ", metrics.mean_absolute_error(test_labels, predictions1_labels))

MAE:  0.5469803958260979


In [23]:
# Em relação a modelagem utilizando a regressão linear, marque a alternativa CORRETA sobre a métrica MSE:  
print("MSE: ", metrics.mean_squared_error(test_labels, predictions1_labels))

MSE:  0.40159703152494497


In [54]:
#Em relação a modelagem utilizando o SVM, marque a alternativa CORRETA sobre a métrica acurácia: 
from sklearn.svm import SVC
#Instanciando o modelo
svc_class = SVC(kernel='rbf')

In [55]:
#preparar os dados
labels = np.array(df_class['Class'])

#ordem das feautures
feauture_list = list(df_class.columns)

#Removendo a coluna alvo do df
df_class = df_class.drop('Class', axis=1)

#Transformando em um array
data_class = np.array(df_class)

#Separando os dados
train_data, test_data, train_labels, test_labels = train_test_split(data_class, labels, test_size=0.35, random_state = 54)

In [56]:
#Treinando o Modelo
svc_class.fit(train_data, train_labels)

SVC()

In [57]:
#Predição
predictions2_labels = svc_class.predict(test_data)

In [58]:
#Avaliando o Modelo
print('Matriz de Confusão\n', metrics.confusion_matrix(test_labels, predictions2_labels))
print('Acuracia:', metrics.accuracy_score(test_labels, predictions2_labels))
print('Acuracia Balanceada por Classe:', metrics.balanced_accuracy_score(test_labels, predictions2_labels))
print('Precision:', metrics.precision_score(test_labels, predictions2_labels))
print('Recall:', metrics.recall_score(test_labels, predictions2_labels))
print('F1:', metrics.f1_score(test_labels, predictions2_labels))
print('AUCROC', metrics.roc_auc_score(test_labels, predictions2_labels))

Matriz de Confusão
 [[199   0]
 [ 63   0]]
Acuracia: 0.7595419847328244
Acuracia Balanceada por Classe: 0.5
Precision: 0.7595419847328244
Recall: 1.0
F1: 0.8633405639913232
AUCROC 0.5


In [60]:
print('Classification Report\n', metrics.classification_report(test_labels, predictions2_labels))

Classification Report
               precision    recall  f1-score   support

           1       0.76      1.00      0.86       199
           2       0.00      0.00      0.00        63

    accuracy                           0.76       262
   macro avg       0.38      0.50      0.43       262
weighted avg       0.58      0.76      0.66       262



In [61]:
# Em relação a modelagem utilizando o Kmeans, marque a alternativa CORRETA sobre o número de clusters: 
df_cluster.head()

class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280%2FOD315_of_diluted_wines  Proline  
0             5.64  1.04                            3.92     1065  
1             4.38  1.05                            3.40     1050  
2             5.68  1.03                            3.17     1185  
3             7.80  0.86                            3.45     1480  
4             4.32  1.04                            2.93      735

In [63]:
df_cluster.columns

Index(['class', 'Alcohol', 'Malic_acid', 'Ash', 'Alcalinity_of_ash',
       'Magnesium', 'Total_phenols', 'Flavanoids', 'Nonflavanoid_phenols',
       'Proanthocyanins', 'Color_intensity', 'Hue',
       'OD280%2FOD315_of_diluted_wines', 'Proline'],
      dtype='object')

In [64]:
#preparar os dados
labels = np.array(df_cluster['class'])

#ordem das feautures
feauture_list = list(df_cluster.columns)

#Removendo a coluna alvo do df
df_cluster = df_cluster.drop('class', axis=1)

#Transformando em um array
data_cluster = np.array(df_cluster)

#Separando os dados
train_data, test_data, train_labels, test_labels = train_test_split(data_cluster, labels, test_size=0.35, random_state = 54)

In [65]:
from sklearn.cluster import KMeans

clustering = KMeans(n_clusters=3, random_state=42)

clustering.fit(train_data)

KMeans(n_clusters=3, random_state=42)

In [66]:
#Predições
predicition1_labels = clustering.predict(test_data)

In [67]:
#Avaliando o Modelo K-means

#Ponto de Vista Não Supervisionado
print('Coeficiente de Silhueta\n', metrics.silhouette_score(test_data, predicition1_labels))
print('\nDavies-Bouldin Score\n', metrics.davies_bouldin_score(test_data, predicition1_labels))

#Ponto de Vista Supervisionado
print('\nMatriz de Contigência\n', metrics.cluster.contingency_matrix(test_labels, predicition1_labels))
print('\nMutual Information\n', metrics.mutual_info_score(test_labels, predicition1_labels))

Coeficiente de Silhueta
 0.5581747258825842

Davies-Bouldin Score
 0.5316199338449924

Matriz de Contigência
 [[ 6 13  0]
 [ 5  1 17]
 [15  0  6]]

Mutual Information
 0.42739927199674965
